// AUTO-GENERATED by tools/bake_audio.py — do not hand-edit.
// Source files: audio/*.{wav,mp3}
// Format: 8-bit unsigned PCM, mono, 16000 Hz
//
// To regenerate: cd firmware/bmo_face_anim && python tools/bake_audio.py

#pragma once
#include <stdint.h>

struct BmoClip {
  const uint8_t *samples;
  uint32_t       length;
  uint32_t       rate;
  const char    *name;
};

static const BmoClip *const BMO_CLIP_TABLE[] = {
};
static constexpr int BMO_CLIP_COUNT = 0;

