[env:esp32s3_bmo_face]
platform = espressif32
board = esp32-s3-devkitc-1
framework = arduino
upload_port = /dev/cu.usbmodem5AE71006121
monitor_port = /dev/cu.usbmodem5AE71006121
monitor_speed = 115200
upload_speed = 921600
lib_deps =
  adafruit/Adafruit GFX Library
  adafruit/Adafruit ST7735 and ST7789 Library
build_unflags =
  -D ARDUINO_USB_MODE=1
  -D ARDUINO_USB_CDC_ON_BOOT=1
build_flags =
  -D ARDUINO_USB_MODE=0
  -D ARDUINO_USB_CDC_ON_BOOT=0
