#!/usr/bin/env python3
"""Bake WAV/MP3 clips into tiny 4-bit IMA ADPCM C arrays.

Usage:
    cd firmware/bmo_face_anim
    python3 tools/bake_audio.py

Clips in audio/*.{wav,mp3} become src/audio_clips.h. Output is mono
16 kHz 4-bit IMA ADPCM, so one second costs about 8 KB of flash instead
of 16 KB for the old raw 8-bit PCM path.
"""

from pathlib import Path
import re
import struct
import subprocess
import sys
import tempfile
import wave


ROOT = Path(__file__).resolve().parent.parent
AUDIO_DIR = ROOT / "audio"
HEADER_OUT = ROOT / "src" / "audio_clips.h"

TARGET_RATE = 16000
TARGET_CHANNELS = 1
TARGET_SAMPLEWIDTH = 2

INDEX_TABLE = [-1, -1, -1, -1, 2, 4, 6, 8,
               -1, -1, -1, -1, 2, 4, 6, 8]
STEP_TABLE = [
    7, 8, 9, 10, 11, 12, 13, 14, 16, 17,
    19, 21, 23, 25, 28, 31, 34, 37, 41, 45,
    50, 55, 60, 66, 73, 80, 88, 97, 107, 118,
    130, 143, 157, 173, 190, 209, 230, 253, 279, 307,
    337, 371, 408, 449, 494, 544, 598, 658, 724, 796,
    876, 963, 1060, 1166, 1282, 1411, 1552, 1707, 1878, 2066,
    2272, 2499, 2749, 3024, 3327, 3660, 4026, 4428, 4871, 5358,
    5894, 6484, 7132, 7845, 8630, 9493, 10442, 11487, 12635, 13899,
    15289, 16818, 18500, 20350, 22385, 24623, 27086, 29794, 32767,
]


def need(message: str) -> None:
    print(message, file=sys.stderr)
    sys.exit(1)


def safe_ident(name: str) -> str:
    ident = re.sub(r"[^A-Za-z0-9_]", "_", name)
    if ident and ident[0].isdigit():
        ident = "_" + ident
    return ident


def clamp16(value: int) -> int:
    if value < -32768:
        return -32768
    if value > 32767:
        return 32767
    return value


def read_s16_wav(path: Path) -> list[int]:
    with wave.open(str(path), "rb") as wav:
        if wav.getnchannels() != TARGET_CHANNELS:
            raise wave.Error("not mono")
        if wav.getframerate() != TARGET_RATE:
            raise wave.Error("wrong sample rate")
        if wav.getsampwidth() != TARGET_SAMPLEWIDTH:
            raise wave.Error("not 16-bit")
        raw = wav.readframes(wav.getnframes())
    return list(struct.unpack("<" + "h" * (len(raw) // 2), raw))


def convert_with_ffmpeg(path: Path) -> list[int]:
    with tempfile.TemporaryDirectory() as tmp:
        wav_path = Path(tmp) / "clip.wav"
        cmd = [
            "ffmpeg", "-hide_banner", "-loglevel", "error", "-y",
            "-i", str(path),
            "-ac", "1",
            "-ar", str(TARGET_RATE),
            "-sample_fmt", "s16",
            str(wav_path),
        ]
        try:
            subprocess.run(cmd, check=True)
        except FileNotFoundError:
            need("ffmpeg is required for non-16k mono WAV/MP3 input.")
        except subprocess.CalledProcessError as exc:
            need(f"ffmpeg failed for {path}: {exc}")
        return read_s16_wav(wav_path)


def load_samples(path: Path) -> list[int]:
    if path.suffix.lower() == ".wav":
        try:
            return read_s16_wav(path)
        except wave.Error:
            return convert_with_ffmpeg(path)
    if path.suffix.lower() == ".mp3":
        return convert_with_ffmpeg(path)
    need(f"Unsupported extension: {path}")
    return []


def encode_ima_adpcm(samples: list[int]) -> tuple[bytes, int, int, int]:
    """Return encoded bytes, sample_count, initial predictor, initial index."""
    if not samples:
        return b"", 0, 0, 0

    predictor = clamp16(samples[0])
    index = 0
    encoded_nibbles: list[int] = []

    for sample in samples[1:]:
        step = STEP_TABLE[index]
        diff = int(sample) - predictor
        code = 0
        if diff < 0:
            code = 8
            diff = -diff

        delta = step >> 3
        if diff >= step:
            code |= 4
            diff -= step
            delta += step
        if diff >= (step >> 1):
            code |= 2
            diff -= step >> 1
            delta += step >> 1
        if diff >= (step >> 2):
            code |= 1
            delta += step >> 2

        if code & 8:
            predictor -= delta
        else:
            predictor += delta
        predictor = clamp16(predictor)
        index += INDEX_TABLE[code & 0x0F]
        if index < 0:
            index = 0
        elif index > 88:
            index = 88
        encoded_nibbles.append(code & 0x0F)

    data = bytearray()
    for i in range(0, len(encoded_nibbles), 2):
        lo = encoded_nibbles[i]
        hi = encoded_nibbles[i + 1] if i + 1 < len(encoded_nibbles) else 0
        data.append(lo | (hi << 4))
    return bytes(data), len(samples), clamp16(samples[0]), 0


def bake_clip(path: Path) -> tuple[str, bytes, int, int, int]:
    samples = load_samples(path)
    data, sample_count, predictor, step_index = encode_ima_adpcm(samples)
    return safe_ident(path.stem), data, sample_count, predictor, step_index


def emit_header(clips: list[tuple[str, bytes, int, int, int]]) -> str:
    lines: list[str] = []
    lines.append("// AUTO-GENERATED by tools/bake_audio.py - do not hand-edit.")
    lines.append("// Source files: audio/*.{wav,mp3}")
    lines.append("// Format: 4-bit IMA ADPCM, mono, 16000 Hz")
    lines.append("//")
    lines.append("// To regenerate: cd firmware/bmo_face_anim && python3 tools/bake_audio.py")
    lines.append("")
    lines.append("#pragma once")
    lines.append("#include <stdint.h>")
    lines.append("")
    lines.append("struct BmoClip {")
    lines.append("  const uint8_t *samples;")
    lines.append("  uint32_t       length;")
    lines.append("  uint32_t       sample_count;")
    lines.append("  uint32_t       rate;")
    lines.append("  int16_t        predictor;")
    lines.append("  uint8_t        step_index;")
    lines.append("  const char    *name;")
    lines.append("};")
    lines.append("")

    for ident, data, sample_count, predictor, step_index in clips:
        seconds = sample_count / TARGET_RATE if TARGET_RATE else 0
        lines.append(f"// {ident}: {len(data)} bytes ({seconds:.2f}s)")
        lines.append(f"static const uint8_t bmo_clip_{ident}_data[] = {{")
        for i in range(0, len(data), 16):
            row = ", ".join(f"0x{b:02X}" for b in data[i:i + 16])
            lines.append(f"  {row},")
        lines.append("};")
        lines.append(f"static const BmoClip bmo_clip_{ident} = {{")
        lines.append(f"  bmo_clip_{ident}_data,")
        lines.append(f"  sizeof(bmo_clip_{ident}_data),")
        lines.append(f"  {sample_count},")
        lines.append(f"  {TARGET_RATE},")
        lines.append(f"  {predictor},")
        lines.append(f"  {step_index},")
        lines.append(f"  \"{ident}\",")
        lines.append("};")
        lines.append("")

    lines.append("static const BmoClip *const BMO_CLIP_TABLE[] = {")
    for ident, *_ in clips:
        lines.append(f"  &bmo_clip_{ident},")
    lines.append("};")
    lines.append(f"static constexpr int BMO_CLIP_COUNT = {len(clips)};")
    lines.append("")
    return "\n".join(lines)


def main() -> None:
    AUDIO_DIR.mkdir(parents=True, exist_ok=True)
    sources = sorted(list(AUDIO_DIR.glob("*.wav")) + list(AUDIO_DIR.glob("*.mp3")))
    if not sources:
        HEADER_OUT.write_text(emit_header([]))
        print(f"No audio in {AUDIO_DIR}. Wrote empty {HEADER_OUT}")
        return

    clips = []
    total = 0
    print(f"Found {len(sources)} clips:")
    for src in sources:
        ident, data, sample_count, predictor, step_index = bake_clip(src)
        clips.append((ident, data, sample_count, predictor, step_index))
        total += len(data)
        print(f"  {src.name:36s} -> {ident:24s} {len(data):6d} bytes ({sample_count/TARGET_RATE:.2f}s)")

    HEADER_OUT.parent.mkdir(parents=True, exist_ok=True)
    HEADER_OUT.write_text(emit_header(clips))
    print(f"\nWrote {HEADER_OUT}")
    print(f"Total ADPCM: {total} bytes ({total/1024:.1f} KB)")
    if total > 80_000:
        print("WARNING: voice pack is over 80 KB. Trim or shorten clips.")


if __name__ == "__main__":
    main()
