#!/usr/bin/env python3
"""
Bake .wav / .mp3 audio clips into a C header array for BMO firmware.

Usage:
    cd firmware/bmo_face_anim
    python tools/bake_audio.py

Drops all clips found in audio/*.{wav,mp3} into src/audio_clips.h as
PROGMEM-friendly uint8_t arrays at 16 kHz 8-bit unsigned PCM mono. The
filename (minus extension) becomes the C identifier, with non-alnum
characters replaced by underscores.

Conversions applied:
  - Stereo -> mono
  - Any sample rate -> 16000 Hz
  - Any bit depth -> 8-bit unsigned PCM (offset 128)
  - MP3 -> WAV (requires `pydub` and ffmpeg)

Result is the smallest reasonable footprint that still sounds clearly
like a voice on a small speaker. Each second of clip ≈ 16 KB of flash.
"""
import os
import re
import sys
import wave
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
AUDIO_DIR = ROOT / "audio"
HEADER_OUT = ROOT / "src" / "audio_clips.h"

TARGET_RATE = 16000
TARGET_CHANNELS = 1
TARGET_SAMPLEWIDTH = 1   # 8-bit unsigned

def need(msg):
    print(msg, file=sys.stderr)
    sys.exit(1)

def safe_ident(name: str) -> str:
    s = re.sub(r"[^A-Za-z0-9_]", "_", name)
    if s and s[0].isdigit():
        s = "_" + s
    return s

def load_with_pydub(path: Path):
    try:
        from pydub import AudioSegment
    except ImportError:
        need(
            "Install pydub first:  pip install pydub\n"
            "And install ffmpeg:   brew install ffmpeg  (macOS)"
        )
    seg = AudioSegment.from_file(str(path))
    seg = seg.set_channels(TARGET_CHANNELS).set_frame_rate(TARGET_RATE)
    # to 8-bit unsigned PCM
    seg = seg.set_sample_width(TARGET_SAMPLEWIDTH)
    return seg.raw_data

def load_with_wave(path: Path):
    """Try to load a WAV file with the stdlib first, fall back to pydub."""
    try:
        with wave.open(str(path), "rb") as w:
            if (w.getnchannels() == TARGET_CHANNELS
                    and w.getframerate() == TARGET_RATE
                    and w.getsampwidth() == TARGET_SAMPLEWIDTH):
                return w.readframes(w.getnframes())
    except wave.Error:
        pass
    return load_with_pydub(path)

def bake_clip(path: Path) -> tuple[str, bytes]:
    ext = path.suffix.lower()
    if ext == ".wav":
        data = load_with_wave(path)
    elif ext == ".mp3":
        data = load_with_pydub(path)
    else:
        need(f"Unsupported extension: {path}")
    return safe_ident(path.stem), data

def emit_header(clips: list[tuple[str, bytes]]) -> str:
    lines = []
    lines.append("// AUTO-GENERATED by tools/bake_audio.py — do not hand-edit.")
    lines.append("// Source files: audio/*.{wav,mp3}")
    lines.append("// Format: 8-bit unsigned PCM, mono, 16000 Hz")
    lines.append("//")
    lines.append("// To regenerate: cd firmware/bmo_face_anim && python tools/bake_audio.py")
    lines.append("")
    lines.append("#pragma once")
    lines.append("#include <stdint.h>")
    lines.append("")
    lines.append("struct BmoClip {")
    lines.append("  const uint8_t *samples;")
    lines.append("  uint32_t       length;")
    lines.append("  uint32_t       rate;")
    lines.append("  const char    *name;")
    lines.append("};")
    lines.append("")

    # one array per clip
    for ident, data in clips:
        lines.append(f"// {ident}: {len(data)} bytes ({len(data)/TARGET_RATE:.2f}s)")
        lines.append(f"static const uint8_t bmo_clip_{ident}_data[] = {{")
        # 16 bytes per row
        for i in range(0, len(data), 16):
            chunk = data[i:i + 16]
            row = ", ".join(f"0x{b:02X}" for b in chunk)
            lines.append(f"  {row},")
        lines.append("};")
        lines.append(f"static const BmoClip bmo_clip_{ident} = {{")
        lines.append(f"  bmo_clip_{ident}_data,")
        lines.append(f"  sizeof(bmo_clip_{ident}_data),")
        lines.append(f"  {TARGET_RATE},")
        lines.append(f"  \"{ident}\",")
        lines.append("};")
        lines.append("")

    # convenience table for lookup-by-name
    lines.append("static const BmoClip *const BMO_CLIP_TABLE[] = {")
    for ident, _ in clips:
        lines.append(f"  &bmo_clip_{ident},")
    lines.append("};")
    lines.append(f"static constexpr int BMO_CLIP_COUNT = {len(clips)};")
    lines.append("")

    return "\n".join(lines) + "\n"

def main():
    if not AUDIO_DIR.exists():
        AUDIO_DIR.mkdir(parents=True)
        print(f"Created {AUDIO_DIR}. Drop your .wav/.mp3 clips here, then re-run.")
        return

    sources = sorted(
        list(AUDIO_DIR.glob("*.wav")) + list(AUDIO_DIR.glob("*.mp3"))
    )
    if not sources:
        print(f"No audio in {AUDIO_DIR}. Drop .wav or .mp3 files there.")
        # still emit an empty header so the firmware compiles
        HEADER_OUT.write_text(emit_header([]))
        print(f"Wrote empty {HEADER_OUT}")
        return

    print(f"Found {len(sources)} clips:")
    clips = []
    total = 0
    for src in sources:
        ident, data = bake_clip(src)
        clips.append((ident, data))
        total += len(data)
        print(f"  {src.name:40s} -> {ident:30s} {len(data):6d} bytes ({len(data)/TARGET_RATE:.2f}s)")

    HEADER_OUT.parent.mkdir(parents=True, exist_ok=True)
    HEADER_OUT.write_text(emit_header(clips))
    print(f"\nWrote {HEADER_OUT}")
    print(f"Total: {total} bytes ({total/1024:.1f} KB)")
    if total > 2_500_000:
        print("WARNING: total > 2.5 MB. May not fit in flash. Trim some clips.")

if __name__ == "__main__":
    main()
